Repository KTB-Sixmen/gitfolio_front, pull requests merged in 2024-12, with the labels that each got.

#92 [Fix] 댓글에 한글이 있으면 기능이 제대로 동작하지 않는 문제 & 이력서 화면 API 에러 시 프로세스 추가
  src/app/(home)/community/_hooks/useResumeQuery.ts
  src/app/(home)/community/resumes/[resumeId]/_components/resume-comment.tsx
  src/app/(home)/community/resumes/[resumeId]/page.tsx
  src/app/(home)/onboarding/_hooks/useOnboardingUpdate.ts
  src/app/(home)/onboarding/repositories/_hooks/useResumeMutation.tsx
  src/app/(myResume)/myResume/[resumeId]/page.tsx
  src/app/api/customFetch.ts
Labels: 🐞 BugFix

#95 ♻️ [Refactor] AI 이력서 수정 시 즉각 반영이 아닌 사용자 확인 프로세스 추가
  src/app/(home)/_components/Footer.tsx
  src/app/(home)/_components/notification-popover.tsx
  src/app/(home)/community/_hooks/useResumeQuery.ts
  src/app/(home)/onboarding/page.tsx
  src/app/(home)/terms-of-service/page.tsx
  src/app/(myResume)/myResume/[resumeId]/_components/AIResumePatchDialog.tsx
  src/app/(myResume)/myResume/[resumeId]/_components/MyResumeDeleteModal.tsx
  src/app/(myResume)/myResume/[resumeId]/hooks/useMyResumePatchMutation.ts
  src/app/(myResume)/myResume/[resumeId]/page.tsx
  src/app/(myResume)/myResume/page.tsx
  src/app/_lib/util.tsx
  src/app/error.tsx
  src/app/store/useDialogOpenStore.ts
  src/lib/utils.ts
Labels: ✨ Feature, 🔨 Refactor

#98 [RE]: ♻️ [Refactor] standalone 으로 도커이미지 용량 최적화
  Dockerfile
  next.config.mjs
Labels: 🔨 Refactor

#100 ♻️ [Refactor] : 추가된 환경변수에 맞게 도커파일, cicd 파일 수정
  .github/workflows/nextjs-cicd.yaml
  .gitignore
  Dockerfile
Labels: ⚙ Setting

#102 🌟 [Feature] 내 이력서 직접 수정하기 기능을 구현한다.
  next.config.mjs
  package-lock.json
  package.json
  public/images/resume_basic_template.png
  public/images/resume_gitfolio_template.png
  public/images/resume_star_template.png
  public/images/resume_template1.png
  public/images/resume_template2.png
  public/images/resume_template3.png
  src/app/(home)/_components/Footer.tsx
  src/app/(home)/_components/header.tsx
  src/app/(home)/_components/notification-popover.tsx
  src/app/(home)/_hooks/usePushNotification.ts
  src/app/(home)/community/_components/community-skeleton.tsx
  src/app/(home)/community/_components/community.tsx
  src/app/(home)/community/resumes/[resumeId]/_hooks/useResumeCommentCreate.ts
  src/app/(home)/edit/_hooks/useProfileUpdate.ts
  src/app/(home)/onboarding/_hooks/useOnboardingUpdate.ts
  src/app/(home)/onboarding/page.tsx
  src/app/(home)/onboarding/repositories/_components/repository.tsx
  src/app/(home)/onboarding/repositories/page.tsx
  src/app/(home)/plan/_components/FAQSection.tsx
  src/app/(home)/plan/_constants/constans.ts
  src/app/(myResume)/myResume/[resumeId]/_components/AIResumePatchDialog.tsx
  src/app/(myResume)/myResume/[resumeId]/edit/_components/ProjectFields.tsx
  src/app/(myResume)/myResume/[resumeId]/edit/_lib/resume-schema.ts
  src/app/(myResume)/myResume/[resumeId]/edit/page.tsx
  src/app/(myResume)/myResume/[resumeId]/hooks/useMyResumePatchMutation.ts
  src/app/(myResume)/myResume/[resumeId]/page.tsx
  src/app/(myResume)/myResume/create/page.tsx
  src/app/api/customFetch.ts
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor, chore

#103 fix: sentry 바운더리 & 파비콘 수정
  src/app/(myResume)/layout.tsx
  src/app/(myResume)/myResume/[resumeId]/_components/ResumeDocument.tsx
  src/app/_components/ErrorBoundary.tsx
  src/app/api/customFetch.ts
  src/app/favicon.ico
Labels: 🔨 Refactor

#104 fix: README.md 수정
  README.md
Labels: 📃 Docs
