Repository KTB-Sixmen/gitfolio_front, pull requests merged in 2024-11, with the labels that each got.

#35 🎨 메인 화면(커뮤니티) 구현
  .eslintrc.json
  .prettierrc
  next.config.mjs
  package-lock.json
  package.json
  public/images/languages/HCL.png
  public/images/languages/Java.png
  src/app/(home)/_components/header-popover.tsx
  src/app/(home)/_components/header.tsx
  src/app/(home)/_hooks/useLogout.tsx
  src/app/(home)/community/_components/community.tsx
  src/app/(home)/community/_hooks/useLikeMutation.ts
  src/app/(home)/community/_hooks/useResumeQuery.ts
  src/app/(home)/community/page.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/onboarding/_components/custom-month-range-picker.tsx
  src/app/(home)/onboarding/_components/onboarding-skeleton.tsx
  src/app/(home)/onboarding/_hooks/useProfileQuery.ts
  src/app/(home)/onboarding/_lib/schema.ts
  src/app/(home)/onboarding/page.tsx
  src/app/(home)/onboarding/repositories/_components/repository-skeleton.tsx
  src/app/(home)/onboarding/repositories/_components/repository.tsx
  src/app/(home)/onboarding/repositories/_hooks/useRepositoryQuery.ts
  src/app/(home)/onboarding/repositories/_hooks/useResumeMutation.tsx
  src/app/globals.css
  src/app/store/useAuthStore.ts
  src/app/store/useToggleStore.ts
  src/app/types/type.ts
  src/components/ui/alert-dialog.tsx
  src/components/ui/menubar.tsx
  src/components/ui/month-range-picker.tsx
  src/components/ui/multi-selector.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/tooltip.tsx
Labels: feature, refactor, chore

#36 🎨 이력서 상세 화면 및 내 이력서 화면 구현
  src/app/(home)/community/resumes/[resumeId]/_components/comment-delete-modal.tsx
  src/app/(home)/community/resumes/[resumeId]/_components/resume-comment.tsx
  src/app/(home)/community/resumes/[resumeId]/_components/resume-skeleton.tsx
  src/app/(home)/community/resumes/[resumeId]/_hooks/useResumeComment.ts
  src/app/(home)/community/resumes/[resumeId]/_hooks/useResumeCommentCreate.ts
  src/app/(home)/community/resumes/[resumeId]/_hooks/useResumeCommentDelete.ts
  src/app/(home)/community/resumes/[resumeId]/page.tsx
  src/app/(home)/myResume/[resumeId]/page.tsx
  src/app/(home)/myResume/_hooks/useMyResumeQuery.ts
  src/app/(home)/myResume/page.tsx
  src/app/(home)/test/page.tsx
Labels: feature

#38 Feature/cicd
  .dockerignore
  .github/workflows/nextjs-cicd.yml
  Dockerfile
Labels: feature, chore

#41 🌟 Feature/#39/sidebar: 이력서 수정 시 텍스트 드래그하여 채팅보낼 수 있는 사이드바 구현
  .prettierrc
  package-lock.json
  package.json
  public/fonts/Pretendard-Bold.ttf
  public/fonts/Pretendard-Regular.ttf
  public/fonts/Pretendard-SemiBold.ttf
  public/fonts/PretendardVariable.woff2
  public/images/default-link.png
  public/images/languages/C#.png
  public/images/languages/C++.png
  public/images/languages/C.png
  public/images/languages/Jupyter Notebook.png
  public/images/linkedin.png
  public/images/notion.png
  public/images/tistory.png
  src/app/(home)/_components/header-popover.tsx
  src/app/(home)/_components/header.tsx
  src/app/(home)/_hooks/useLogout.tsx
  src/app/(home)/community/_components/community-skeleton.tsx
  src/app/(home)/community/_components/community.tsx
  src/app/(home)/community/page.tsx
  src/app/(home)/community/resumes/[resumeId]/page.tsx
  src/app/(home)/myResume/[resumeId]/page.tsx
  src/app/(home)/myResume/_components/my-resume-skeleton.tsx
  src/app/(home)/myResume/page.tsx
  src/app/(home)/onboarding/dummy.ts
  src/app/(home)/onboarding/repositories/_components/repository.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/ui/multi-selector.tsx
Labels: feature, fix

#42 🐛 [Fix] 이력서 pdf 생성 시 문제 해결 #40
  src/app/(home)/myResume/[resumeId]/_components/PdfDownloadButton.tsx
  src/app/(home)/myResume/[resumeId]/_components/ResumeDocument.tsx
  src/app/(home)/onboarding/page.tsx
  src/app/(home)/onboarding/repositories/_hooks/useResumeMutation.tsx
  src/app/(home)/onboarding/repositories/page.tsx
Labels: fix, refactor

#46 ♻️ [Refactor] 레파지토리 선택 시 사용자 요구 사항 받도록 수정 #45
  src/app/(home)/onboarding/repositories/_components/repository.tsx
Labels: refactor

#47 hotfix: react-to-pdf 임포트 제거
  src/app/(home)/test/page.tsx
Labels: fix

#52 ♻️ [Refactor] 중간 평가 전 점검 이슈 #51
  package-lock.json
  package.json
  src/app/(home)/_components/header-popover.tsx
  src/app/(home)/_components/header.tsx
  src/app/(home)/_components/notification-popover.tsx
  src/app/(home)/community/_components/community.tsx
  src/app/(home)/community/_hooks/useLikeMutation.ts
  src/app/(home)/community/resumes/[resumeId]/_components/resume-comment.tsx
  src/app/(home)/community/resumes/[resumeId]/_hooks/useResumeCommentCreate.ts
  src/app/(home)/highlight/page.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/myResume/[resumeId]/page.tsx
  src/app/(home)/myResume/_hooks/useMyResumeQuery.ts
  src/app/(home)/myResume/page.tsx
  src/app/(home)/onboarding/repositories/_components/repository-skeleton.tsx
  src/app/(home)/onboarding/repositories/_hooks/useResumeMutation.tsx
Labels: fix, refactor

#55 🐛 Feature: 버그 수정 및 내 정보 수정 화면 구현
  next.config.mjs
  package-lock.json
  package.json
  src/app/(home)/_components/header-popover.tsx
  src/app/(home)/_components/header.tsx
  src/app/(home)/_components/notification-popover.tsx
  src/app/(home)/_hooks/useNotificationMutation.ts
  src/app/(home)/_hooks/useNotificationQuery.ts
  src/app/(home)/community/_components/community.tsx
  src/app/(home)/community/_hooks/useLikeMutation2.ts
  src/app/(home)/community/_hooks/useResumeQuery.ts
  src/app/(home)/community/resumes/[resumeId]/page.tsx
  src/app/(home)/edit/_components/ProfileEdit.tsx
  src/app/(home)/edit/_hooks/useProfileUpdate.ts
  src/app/(home)/edit/_lib/schema.ts
  src/app/(home)/edit/page.tsx
  src/app/(home)/myResume/[resumeId]/page.tsx
  src/app/(home)/onboarding/_hooks/useProfileQuery.ts
  src/app/(home)/onboarding/repositories/_hooks/useResumeMutation.tsx
  tailwind.config.ts
Labels: feature, fix, refactor, chore

#56 🚑 hotfix: next config 파일 수정
  next.config.mjs
  src/app/(home)/_components/header-popover.tsx
Labels: fix

#58 🚑 hotfix: remove console
  src/app/(home)/community/_components/community.tsx
  src/app/(home)/layout.tsx
Labels: fix

#60 🚑 hotfix: 이미지 url 임시 변경
  src/app/(home)/_hooks/useNotificationQuery.ts
  src/app/(home)/community/_components/community.tsx
  src/app/(home)/myResume/[resumeId]/page.tsx
Labels: fix

#65 hotfix: remove replace
  src/app/(home)/community/_components/community.tsx
Labels: fix

#69 [Feature] 이력서 생성 시 공개 여부 입력 받기 #68
  package-lock.json
  package.json
  src/app/(home)/community/_hooks/useResumeQuery.ts
  src/app/(home)/myResume/[resumeId]/page.tsx
  src/app/(home)/myResume/_hooks/useMyResumeQuery.ts
  src/app/(home)/myResume/_hooks/useMyResumeVisibilityMutation.ts
  src/app/(home)/myResume/page.tsx
  src/app/(home)/onboarding/repositories/_components/repository.tsx
  src/app/(home)/onboarding/repositories/_hooks/useResumeMutation.tsx
  src/components/ui/switch.tsx
Labels: feature

#71 feat: sentry 설치 및 설정
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(home)/onboarding/repositories/_hooks/useResumeMutation.tsx
  src/app/api/sentry-example-api/route.ts
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/sentry-example-page/page.tsx
  src/instrumentation.ts
Labels: feature
